name: 'google-chat-notifications'
description: 'Google Chat Notifications for GitHub Actions'
author: 'nakamuraos'
inputs:
  name:
    description: 'job name.'
    required: true
  url:
    description: 'google chat webhook url.'
    required: true
  status:
    description: 'job status.'
    required: true
runs:
  using: 'node14'
  main: 'dist/index.js'
branding:
  icon: 'bell'
  color: 'green'